### ISSUE TITLE
Can create context?

### ISSUE THREAD

**Issue by Muthurajj** [danubetech/key-formats-java#13]
Can i create new context for my project, if so how to create it?

and also how to create id in credential subject

**Comment by peacekeeper** [comment]
Is this a question about key-formats-java, or maybe one of our other libraries ld-signatures-java or verifiable-credentials-java?

**Comment by Muthurajj** [comment]
this is about verifiable-credentials-java library

**Comment by peacekeeper** [comment]
Could you please create an issue in the other library? https://github.com/danubetech/verifiable-credentials-java

Thanks! Closing.

**Comment by Muthurajj** [comment]
Can you pls update in that library
