### ISSUE TITLE
Interop issue with ES256 signature format

### ISSUE THREAD

**Issue by psteniusubi** [danubetech/key-formats-java#14]
Java JCA expects ES256 signature value to be R and S values encoded as a ASN.1/DER object.
JWS expects ES256 signature value to be R and S values concatenated.
For JWS interop there needs to be conversion between the two formats.

For more details see

https://www.rfc-editor.org/rfc/rfc7518#section-3.4
https://www.rfc-editor.org/rfc/rfc7515#appendix-A.3.1

Other implementations

https://bitbucket.org/b_c/jose4j/src/master/src/main/java/org/jose4j/jws/EcdsaUsingShaAlgorithm.java
https://bitbucket.org/connect2id/nimbus-jose-jwt/src/master/src/main/java/com/nimbusds/jose/crypto/impl/ECDSA.java

**Comment by peacekeeper** [comment]
Thanks for pointing this out, I created a PR that should fix this bug.

**Comment by psteniusubi** [comment]
The PR seems to fix this issue for me. Thanks. 
I run into two other issues: x5t#S256 is not supported and x5c has incompatible type. JWK spec defines x5c as array of string.

**Comment by peacekeeper** [comment]
I think I fixed that too now in https://github.com/danubetech/key-formats-java/commit/e75b9985c44a78597b94cbcb51a907190c24cd6b, would you mind checking again?
