### ISSUE TITLE
Release last version

### ISSUE THREAD

**Issue by fabrii** [danubetech/key-formats-java#19]
Hi @peacekeeper.  First of all, thanks for all these digital credentials java libraries. Great work! 

I wanted to know if it is possible to release the latest changes of the key-formats-java library to your nexus repository, and also update ld-signatures-java, and verifiable-credentials-java libraries with the new references. I can help you with the PR.

Thanks a lot!

**Comment by peacekeeper** [comment]
@fabrii thanks for your comment, good to hear the libraries are useful for you! Yes we can do this, no problem.

@BernhardFuchs can you help with these releases?

**Comment by BernhardFuchs** [comment]
@fabrii The three libraries are all released with the latest versions of dependecies.

**Comment by fabrii** [comment]
Nice! Thank you both :smiley:
