### ISSUE TITLE
Conflicts with Android's builtin apache commons codec library

### ISSUE THREAD

**Issue by kenneth-leong-gt** [danubetech/key-formats-java#22]
There seems to be a conflict with Android's internal `org.apache.commons.codec`. So when verifying a JsonLD i will get an exception like below

```
NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
```

Is it possible to use a shaded org.apache.commons.codec jar or include a class that uses a different base64 implementaton other than apache commons?

**Comment by peacekeeper** [comment]
Hello @kenneth-leong-gt thanks for raising this! I'm not very experienced with Android, but I just pushed an update that avoids newer methods of the Base64 and (I think) should be compatible with older APIs:
https://github.com/danubetech/key-formats-java/commit/6e0e3c423a73c57361b26d482cdacc27c04f0891

Could you maybe try if it works with this change?

**Comment by kenneth-leong-gt** [comment]
Hi Thanks for the update. The issue i was facing stemmed from the `JWK` class using the apache commons codec's `Base64.decodeBase64` method while doing the below

```kotlin
val parsedJwk = JWK.fromJson(jwkString)
val byteVerifier = PublicKeyVerifierFactory.publicKeyVerifierForJWK(parsedJwk, getPubKeyAlgo(ldProof))
```

FYI in Android, it will always uses its own version so apache commons codec which maybe of a lower version, even if in my app, i bundle my own apache commons codec library in. This has been an [issue](https://issuetracker.google.com/issues/37033030) for quite some time in Android 

I think your change for using java.util's `Base64` class should work. 
How can i get this change? is it in a snapshot? 

FYI in the meantime i did my own dirty workaround by using this instead
```
val parsedJwk = JWK.fromJson(jwkString)
val nimbusJwk = com.nimbusds.jose.jwk.JWK.parse(jwkString)
val byteVerifier = PublicKeyVerifierFactory.publicKeyVerifierForKey(
            KeyTypeName_for_JWK.keyTypeName_for_JWK(parsedJwk),
            getPubKeyAlgo(ldProof),
            JWK_to_PublicKey.JWK_to_anyPublicKey(nimbusJwk, webOfTrustJwk)
        )
````
where i used the nimbus jose implementation of JWK to get the decoded base64 byte array for the key material. And I modified and created my own `JWK_to_publicKey` class
[JWK_to_publicKey.txt](https://github.com/danubetech/key-formats-java/files/12364889/JWK_to_publicKey.txt)

**Comment by peacekeeper** [comment]
You should be able to try the latest version as follows:

```
<repositories>
	<repository>
		<id>danubetech-maven-public</id>
		<url>https://repo.danubetech.com/repository/maven-public/</url>
	</repository>
</repositories>

<dependency>
	<groupId>com.danubetech</groupId>
	<artifactId>key-formats-java</artifactId>
	<version>1.9-SNAPSHOT</version>
</dependency>
```

(or Gradle equivalent)

**Comment by peacekeeper** [comment]
@kenneth-leong-gt Has this been fixed, can we close the issue?

**Comment by kenneth-leong-gt** [comment]
yup thanks, latest version works.
